{ nixpkgs }:
''
  abbr --add --global -- add 'git add'
  abbr --add --global -- amend 'git commit --amend'
  abbr --add --global -- cherry 'git cherry-pick'
  abbr --add --global -- ci 'git commit'
  abbr --add --global -- ci-empty 'git ci --allow-empty -m empty'
  abbr --add --global -- clip 'xclip -selection clipboard'
  abbr --add --global -- clone 'git clone'
  abbr --add --global -- co 'git checkout'
  abbr --add --global -- fetch 'git fetch'
  abbr --add --global -- log 'git log'
  abbr --add --global -- merge 'git merge'
  abbr --add --global -- pull 'git pull'
  abbr --add --global -- push 'git push'
  abbr --add --global -- rebase 'git rebase'
  abbr --add --global -- restart 'sudo systemctl restart'
  abbr --add --global -- revert 'git revert'
  abbr --add --global -- show 'git show'
  abbr --add --global -- staged 'git diff --cached'
  abbr --add --global -- start 'sudo systemctl start'
  abbr --add --global -- stash 'git stash'
  abbr --add --global -- stop 'sudo systemctl stop'
  abbr --add --global -- trash 'gio trash'
''
